### PR TITLE
Update strip padding on small screens

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Updated the small screen padding for `is-deep` and `is-shallow`. Added padding for the default `p-strip`.

## QA
- Pull down branch and run `gulp jekyll`
- Go to each strip and make sure the padding matches [the spec](https://github.com/ubuntudesign/vanilla-brochure-theme-design/blob/master/Strip/strip.md).

## Details
Fixes https://github.com/vanilla-framework/vanilla-brochure-theme/issues/80

### CODE REVIEW

**Comment by barrymcgee** [comment]
@anthonydillon What's the next steps on this?

**Comment by anthonydillon** [comment]
Trying to find a moment to work on it. I will give it some thought tonight.

**Comment by anthonydillon** [comment]
@barrymcgee updated by inheriting the strip pattern to effect all strips. Ready for another review.

**Comment by barrymcgee** [comment]
Looks good 👍🏻

**Pull request merged**
