### PR TITLE
Install example-js in docs

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Replaced the hard coded examples in the docs with example-js. Updated some docs with basic descriptions.

## QA
- Make sure you pull down [docs.vanillaframework.io repo](https://github.com/ubuntudesign/docs.vanillaframework.io/)
- Pull down this branch in a parent directory to the docs one
- cd into the docs.vanillaframework.io repo
- Replace `build-html` file content with the content below:
``` bash
documentation-builder --base-directory ../vanilla-brochure-theme/docs  \
                      --site-root '/en/'  \
                      --output-path .  \
                      --template-path template.html  \
                      --tag-manager-code 'GTM-K92JCQ'  \
                      --no-link-extensions \
                      --force
```
- Run `./build-html`
- Then run `caddy`
- Go to http://127.0.0.1:8543/en/
- Click through the docs and check example js is rendering all examples

## Details
Fixes https://github.com/vanilla-framework/vanilla-brochure-theme/issues/97 https://github.com/vanilla-framework/vanilla-brochure-theme/issues/98

### CODE REVIEW

**Comment by anthonydillon** [comment]
Bundled the linking to Vanilla with this PR as it has structural changes and is still not reviewed.

**Comment by barrymcgee** [comment]
Looking good, just  a couple of questions:

- The indentation of the code seems to be off
- The 'Vanilla' footer at the bottom of each page seems to have inadequate top padding

**Comment by anthonydillon** [comment]
> The indentation of the code seems to be off
- This will be resolved with this PR https://github.com/vanilla-framework/vanilla-brochure-theme/pull/102
- And improved further by the update to example-js https://github.com/ubuntudesign/docs.vanillaframework.io/pull/97

> The 'Vanilla' footer at the bottom of each page seems to have inadequate top padding
- This is using rare Vanilla. I think this will be improved when docs-theme upgrades Vanilla to the latest version.

**Comment by barrymcgee** [comment]
🙌🏻

**Pull request merged**
